// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Background from "@/components/background";
// import Header from "@/components/header";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {/* <div className="bg-gradient-to-br from-cyan-600 to-sky-600"> */}
//           <Background/>
//           <Header/>
//           {children}
//       </body>
//     </html>
//   );
// }

import "../globals.css"
import type { Metadata } from "next"
import Header from "@/components/header"
import Footer from "@/components/footer"
import type React from "react" // Added import for React
import { CartSidebar } from "@/components/cart/cart-sidebar"
import Providers from "@/providers"
import ComingSoon from "./_sections/coming-soon"

export const metadata: Metadata = {
  title: "Handcrafted Ceramics",
  icons : "/img/seahorse-logo.png",
  description: "Beautiful homemade ceramics from Coastal California",
}

export default async function RootLayout({
  children,
  modal
}: Readonly<{
  children: React.ReactNode
  modal: React.ReactNode
}>) {

  if(process.env.COMING_SOON){
    return (
      <>
        <ComingSoon/>
      </>
    )
  }
  else
    return (
        <>
          {/* <Background/> */}
          <Providers>
              <Header />
              {modal}
              {children}
              <Footer />
              <CartSidebar/>
          </Providers>
        </>
    )
}

