// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Background from "@/components/background";
// import Header from "@/components/header";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {/* <div className="bg-gradient-to-br from-cyan-600 to-sky-600"> */}
//           <Background/>
//           <Header/>
//           {children}
//       </body>
//     </html>
//   );
// }

import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import type React from "react" // Added import for React

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Handcrafted Ceramics",
  icons : "/img/seahorse-logo.png",
  description: "Beautiful homemade ceramics from Coastal California",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
  modal: React.ReactNode
}>) {

  return (
    <html lang="en">
      <body className={`${inter.className} bg-gradient-to-r from-sky-300 to-cyan-100 text-gray-900`}>
            {children}
      </body>
    </html>
  )
}

